# Practicing numpy 

**1.1 Import the numpy package under the name `np`**

In [2]:
import numpy as np

**1.2 Print the list of all members of numpy**

In [3]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import

**1.3 Print the number of all functions, contants etc., which are members of numpy**

In [4]:
len(dir(np))

607

**1.4 Print the help for numpy.array**

In [7]:
np.array?
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

**2.1 Create a vector of length 10, with all it's elements set to 0**

In [8]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

**2.2 Create a vector of length 10, with all it's elements set to 4, except for the third element which is set to 3. Make sure all elements are of type int**

In [12]:
z = np.zeros(10)+4
z[2]=3
print(z)

[ 4.  4.  3.  4.  4.  4.  4.  4.  4.  4.]


**3.1  Create a vector of size 10, with values going from 1 to 10**

In [14]:
z = np.arange(1,11)
print(z)

[ 1  2  3  4  5  6  7  8  9 10]


**3.2  Create a vector of size 10, with values going from 10 to 1 (decreasing order)**

In [18]:
Z = np.arange(11,1,-1)
print(Z)

[11 10  9  8  7  6  5  4  3  2]


**3.3  Find the indices of all entries bigger than 4 in the vector above**

In [22]:
np.where(Z>4)

(array([0, 1, 2, 3, 4, 5, 6]),)

**4.1  Create a 5x6 matrix with normal random values**

In [23]:
Z= np.random.randn(5,6)
print(Z)

[[ 1.47252237  0.94830581 -0.48619445  0.67841932 -1.32829113  0.25884619]
 [-0.38651351  0.82764551  2.83673304  1.55187293 -0.15450037 -1.39346761]
 [-1.47421147  0.35409371 -0.81763842 -0.30371191  0.63945253  0.88258307]
 [-0.76363023  0.61008984  0.32133911 -0.8478135  -0.25208665 -1.92204569]
 [ 0.35424463  0.54839723 -0.68749108  1.96899611 -0.0922357  -0.33600982]]


**4.2 Create a 3x4x5 array with normal random values**

In [25]:
Z = np.random.randn(3,4,5)
print(Z)

[[[ 0.79419719 -0.39283345 -0.72406526 -0.65947257 -1.52085961]
  [-0.12590777 -0.37953272 -1.19657225  0.16844912  1.5448269 ]
  [ 0.81580205  0.31638955 -1.29556604  1.54455417  1.2517007 ]
  [-2.18242219 -1.08581113 -1.15635227  0.46594596  1.32025118]]

 [[-1.45019508 -1.5338043  -0.32540159 -0.95715924 -0.04180473]
  [ 0.37405967  0.62513386  1.29266242 -0.57074156 -0.19751066]
  [ 0.43780387  0.03255031 -0.32267169  0.7301506   0.67841177]
  [-1.0144681   1.28590629  0.79355855 -1.99291701  0.8312243 ]]

 [[ 1.95268013  0.49864944  0.19830547  1.38971404 -0.34203295]
  [ 1.03397905 -0.43777304  0.50072935 -0.11673296 -1.73890465]
  [ 0.53117723  0.2720409   2.37005708 -1.2660781  -0.01092234]
  [-2.83638481  1.24897846  1.02632606 -0.31787005 -1.86678224]]]


**5.1 Create a 5x6 matrix with random values and find the minimum and maximum values**

In [27]:
Z = np.random.randn(5,6)
Zmin,Zmax = Z.min(),Z.max()
print(Zmin, Zmax)

2.49864801238 -1.62923020956


**5.2 Find the min value in each column of the matrix above**

In [29]:
Zmin = Z.min(axis=0)
print(Zmin)

[-1.34140888 -1.20307598 -1.62923021 -1.14535334 -1.4717475  -0.06550587]


**5.3 Find the max value in each row of the matrix above**

In [30]:
Zmax = Z.max(axis=1)
print(Zmax)

[ 0.69068399  0.78903374  1.093799    1.05453132  2.49864801]


**6.1 Create a random vector of length 5, and normalize it to have zero mean**

In [31]:
A = np.random.rand(5)
A-=A.mean()
print(A)

[-0.09918549  0.40386819 -0.14912839 -0.07522986 -0.08032446]


**6.2 Create a random matrix with 3 rows and 5 columns, and normalize each of its rows to have zero mean**

In [35]:
Z = np.random.rand(3,5)
print(Z)
print('Z row mean')
print(Z.mean(axis=1,keepdims=True))
print('Centered Z')
print(Z - Z.mean(axis=1,keepdims=True))


[[ 0.70206325  0.22359403  0.02710275  0.61429271  0.38959121]
 [ 0.55677102  0.66378034  0.46203939  0.00671063  0.88474763]
 [ 0.98618248  0.9622352   0.91403775  0.14157628  0.64602616]]
Z row mean
[[ 0.39132879]
 [ 0.5148098 ]
 [ 0.73001158]]
Centered Z
[[ 0.31073446 -0.16773476 -0.36422604  0.22296392 -0.00173758]
 [ 0.04196122  0.14897054 -0.05277041 -0.50809918  0.36993783]
 [ 0.25617091  0.23222363  0.18402618 -0.5884353  -0.08398541]]


**7.1 Create a vector with a random permutation of all integers from 0 to 20**

In [36]:
Z= np.random.permutation(21)
print(Z)

[ 5 11 18 12  8  7  3  4  2 14  1 15 10  0  6 19 13 17 16  9 20]


**7.2 Print the indices of all elements larger than 15 in the vector above**

In [38]:
print(np.where(Z>15)[0])

[ 2 15 17 18 20]


**8.1 Create a vector of size 5 with values equally spaced between 0 to 1, both included**

In [39]:
Z = np.linspace(0,1,5)
print(Z)

[ 0.    0.25  0.5   0.75  1.  ]


**8.2 Create a vector of size 5 with values ranging from 0 to 1, excluding 1**

In [40]:
Z = np.linspace(0,1,5,endpoint=False)
print(Z)


[ 0.   0.2  0.4  0.6  0.8]


**8.3 Create a vector of size 5 with values ranging from 0 to 1, both excluded**

**9. Create a random vector of size 20 and sort it in ascending order**

In [42]:
Z = np.random.random(20)
Z.sort()
print(Z)

[ 0.06265877  0.06546505  0.12738465  0.13490962  0.14013661  0.16986558
  0.34766371  0.46004293  0.50112652  0.58059855  0.62193847  0.68549179
  0.69991649  0.71894475  0.81206192  0.85325457  0.87440329  0.94712221
  0.95021024  0.97537937]


**10. Create a random vector of size 5 and replace its maximal value with the number 0**

In [44]:
Z  = np.random.random(5)
i = Z.argmax()
Z[i] =0
print(Z)

[ 0.20307077  0.          0.03792811  0.47538615  0.4603968 ]


**11. Create a random vector of size 5x5, and sort it by the third column?**

In [49]:
Z = np.random.rand(5,5)
print(Z)
print(Z[:,2].argsort())
print(Z[Z[:,2].argsort()])


[[ 0.24807224  0.66228097  0.51461433  0.11695267  0.83449328]
 [ 0.27328906  0.15395824  0.6435156   0.43164379  0.89744107]
 [ 0.6493611   0.08795676  0.88177146  0.33780636  0.52248014]
 [ 0.78999149  0.74549665  0.34952269  0.21772751  0.52951754]
 [ 0.52838668  0.16257627  0.98507095  0.77614365  0.61648264]]
[3 0 1 2 4]
[[ 0.78999149  0.74549665  0.34952269  0.21772751  0.52951754]
 [ 0.24807224  0.66228097  0.51461433  0.11695267  0.83449328]
 [ 0.27328906  0.15395824  0.6435156   0.43164379  0.89744107]
 [ 0.6493611   0.08795676  0.88177146  0.33780636  0.52248014]
 [ 0.52838668  0.16257627  0.98507095  0.77614365  0.61648264]]


**12. Create a random 3D array of size 10x20x3, and reshape it into a 2D array of shape 200x3**

**13. Create a random vector x of length 5, compute $x^7=[x_0^7, x_1^7,x_2^7,x_3^7,x_4^7]$ **

**14.1 Compute the euclidean distance between $x=[2.1,4.6,-0.3,4.7]$ and $z=[0.2,-10.1,6.3,0]$ **

**Reminder**: the euclidean distance between any $x=[x_0,x_1,\ldots,x_N]$ and $z=[z_0,z_1,\ldots,z_N]$ is given by

$\text{distance}(x,z) = \sqrt{(x_0-z_0)^2+(x_1-z_1)^2+\ldots+(x_N-z_N)^2}$

In [64]:
x= np.array([2.1,4.6,-0.3,4.7])
z = np.array([0.2,-10.1,6.3,0])
print(x,z)
y = x - z
print(y)
y = y * y
print(y)

d = np.sqrt(sum(y))
print(d)

[ 2.1  4.6 -0.3  4.7] [  0.2 -10.1   6.3   0. ]
[  1.9  14.7  -6.6   4.7]
[   3.61  216.09   43.56   22.09]
16.8923059409


**14.2 Compute the euclidean distance between each row of the matrix $X = \left[\begin{array}{cc} 
2.1 & 4.6 & -0.3 & 4.7\\
0 & 3.2 & 17 & -2
\end{array}\right]$ and every row of the matrix $Z = \left[\begin{array}{cc} 
0.2 & -10.1 & 6.3 & 0\\
-6.2 & -1 & 3 & 2.1
\end{array}\right]$**


In [74]:
X = np.array([[2.1,4.6,-0.3,47],[0,3.2,17,-2]])
print(X)
Z = np.array([[0.2,-10.1,6.3,0],[-6.2,-1,3,2.1]])
distances = np.zeros((2,2))
for n in range(2):
    for m in range(2):
        distances[n,m] = np.sqrt(np.power(x[n]-z[m],2).sum())
              

[[  2.1   4.6  -0.3  47. ]
 [  0.    3.2  17.   -2. ]]


**14.3 Repeat the computation above using the function `cdist` from `scipy.spatial.distance`**
```python
# Run this import in a code cell, and use cdist to execute the computation above
from scipy.spatial.distance import cdist
cdist?
```

In [69]:
from scipy.spatial.distance import cdist
cdist?

In [71]:
cdist(X,Z)

array([[ 49.72182619,  46.12103642],
       [ 17.18778636,  16.39786571]])